// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbQN1NxMYZqmcRUwX235HZg2oklMMsvaA',
    appId: '1:196671810782:android:93f69de20e6a0a43a1664f',
    messagingSenderId: '196671810782',
    projectId: 'amplifymusic-c0035',
    storageBucket: 'amplifymusic-c0035.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn3VQXmGb0DSpVDICFgTmSuJdWUS-KUyk',
    appId: '1:196671810782:ios:00fa98dc2dc6f305a1664f',
    messagingSenderId: '196671810782',
    projectId: 'amplifymusic-c0035',
    storageBucket: 'amplifymusic-c0035.appspot.com',
    iosBundleId: 'com.example.amplifyMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn3VQXmGb0DSpVDICFgTmSuJdWUS-KUyk',
    appId: '1:196671810782:ios:00fa98dc2dc6f305a1664f',
    messagingSenderId: '196671810782',
    projectId: 'amplifymusic-c0035',
    storageBucket: 'amplifymusic-c0035.appspot.com',
    iosBundleId: 'com.example.amplifyMusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVsKhcZjXsUaJYE2q4DOaNCKSylLNOaas',
    appId: '1:196671810782:web:420eedd81184fcb0a1664f',
    messagingSenderId: '196671810782',
    projectId: 'amplifymusic-c0035',
    authDomain: 'amplifymusic-c0035.firebaseapp.com',
    storageBucket: 'amplifymusic-c0035.appspot.com',
    measurementId: 'G-S2B8BFNTDX',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVsKhcZjXsUaJYE2q4DOaNCKSylLNOaas',
    appId: '1:196671810782:web:420eedd81184fcb0a1664f',
    messagingSenderId: '196671810782',
    projectId: 'amplifymusic-c0035',
    authDomain: 'amplifymusic-c0035.firebaseapp.com',
    storageBucket: 'amplifymusic-c0035.appspot.com',
    measurementId: 'G-S2B8BFNTDX',
  );
}
