name: Flutter Web Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'  # Use your Flutter version here

      # 3. Get Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Build Flutter Web Release
      - name: Build web
        run: flutter build web --release

      # 5. Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AMPLIFYMUSIC_C0035 }}"
          channelId: live
          projectId: amplify-music  # Replace with your actual Firebase project ID if different
